begin;

create table if not exists documents (
    id bigint generated by default as identity primary key,
    source_name text not null,
    source_page_url text not null,
    source_file_url text not null,
    base_document_number text not null,
    base_document_date date not null,
    edition_date date,
    file_hash text not null unique,
    row_count integer not null check (row_count > 0),
    loaded_at timestamptz not null default now()
);

create table if not exists territory_status_history (
    id bigint generated by default as identity primary key,
    source_document_id bigint not null references documents(id) on delete cascade,
    record_key text not null,
    full_code text not null,
    hromada_code_7 text,
    territory_name text not null,
    oblast text,
    rayon text,
    category text not null,
    status_from date,
    status_to date,
    created_at timestamptz not null default now(),
    constraint uq_territory_snapshot_record unique (source_document_id, record_key),
    constraint ck_territory_code check (full_code ~ '^UA[0-9]{7,}$'),
    constraint ck_status_dates check (
        status_to is null or status_from is null or status_to >= status_from
    )
);

create table if not exists territory_changes (
    id bigint generated by default as identity primary key,
    source_document_id bigint not null references documents(id) on delete cascade,
    previous_document_id bigint references documents(id) on delete set null,
    change_type text not null check (change_type in ('ADDED', 'REMOVED', 'MODIFIED')),
    record_key text not null,
    before_data jsonb,
    after_data jsonb,
    created_at timestamptz not null default now()
);

create index if not exists idx_documents_loaded_at
    on documents (loaded_at desc);
create index if not exists idx_territory_document
    on territory_status_history (source_document_id);
create index if not exists idx_territory_full_code
    on territory_status_history (full_code);
create index if not exists idx_territory_hromada_code
    on territory_status_history (hromada_code_7);
create index if not exists idx_territory_oblast_rayon
    on territory_status_history (oblast, rayon);
create index if not exists idx_territory_category_dates
    on territory_status_history (category, status_from, status_to);
create index if not exists idx_changes_document_type
    on territory_changes (source_document_id, change_type);

create or replace view latest_document as
select d.*
from documents d
order by d.loaded_at desc, d.id desc
limit 1;

create or replace view current_territory_status as
select
    t.source_document_id,
    t.record_key,
    t.full_code,
    t.hromada_code_7,
    t.territory_name,
    t.oblast,
    t.rayon,
    t.category,
    t.status_from,
    t.status_to,
    d.loaded_at
from territory_status_history t
join latest_document d on d.id = t.source_document_id;

commit;
